# -*- coding: utf-8 -*-
"""Copy_of_Question_2_update_MA14Apr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/MORGS-97/ASSIGNMENT-2-GROUP-60/blob/main/Copy_of_Question_2_update_MA14Apr.ipynb
"""

#Enter Inputs for Shift1 & Shift2
shift1 = int(input("Enter Shift 1: "))
shift2 = int(input("Enter Shift 2: "))
print("\n")


#Encryption function
def encrypte_file(filename):
  with open(filename, "r") as infile:
    text = infile.read()


    #Requirements (Lowercase)
    encrypted_text = ""
    for char in text:
      if char.islower() and 'a' <= char <= 'm':
        shift = shift1 * shift2
        new_char = chr(((ord(char) - ord('a') + shift) % 26) + ord('a'))
        encrypted_text += new_char

      elif char.islower() and 'n' <= char <= 'z':
        shift = shift1 + shift2
        new_char = chr(((ord(char) - ord('a')) - shift) % 26 + ord('a'))
        encrypted_text += new_char


      #Requirements (Uppercase)
      elif char.isupper() and "A" <= char <= "M":
        shift = shift1
        new_char = chr(((ord(char) - ord('A')) - shift) %26 + ord('A'))
        encrypted_text += new_char

      elif char.isupper() and "N" <= char <= "Z":
        shift = shift2 ** 2
        new_char = chr(((ord(char) - ord('A')) + shift) %26 + ord('A'))
        encrypted_text += new_char

      else:
        encrypted_text += char


    #Create encrypted file & print text
    print(encrypted_text)
    with open("encrypted_text.txt", "w") as outfile:
      outfile.write(encrypted_text)
    print('\n')
    print("New file created: encrypted_text.txt")


#Call encrypt function
encrypte_file("raw_text.txt")


#Decryption Function
def decrypt_file(filename):
  with open("encrypted_text.txt", "r") as infile:
    text = infile.read()
  lower_shift1 = shift1 * shift2
  lower_shift2 = shift1 + shift2
  upper_shift1 = shift1
  upper_shift2 = shift2 ** 2
  decrypted_text = ""

  for char in text:


    #Lowercase Decryption
    if char.islower():

      option_1 = chr(((ord(char) - ord('a') - lower_shift1) % 26) + ord('a'))
      option_2 = chr(((ord(char) - ord('a')) + lower_shift2) % 26 + ord('a'))

      valid_1 = 'a' <= option_1 <= 'm'
      valid_2 = 'n' <= option_2 <= 'z'

      if valid_1 and not valid_2:
        decrypted_text += option_1

      elif valid_2 and not valid_1:
        decrypted_text += option_2

      elif valid_1 and valid_2:
        decrypted_text += option_2


    #Uppercase Decryption
    elif char.isupper():
      option_1 = chr(((ord(char) - ord('A') + upper_shift1) % 26) + ord('A'))
      option_2 = chr(((ord(char) - ord('A')) - upper_shift2) % 26 + ord('A'))

      valid_1 = 'A' <= option_1 <= 'M'
      valid_2 = 'N' <= option_2 <= 'Z'

      if valid_1 and not valid_2:
        decrypted_text += option_1

      elif valid_2 and not valid_1:
        decrypted_text += option_2

      elif valid_1 and valid_2:
        decrypted_text += option_2

    else:
      decrypted_text += char


  #Create decrypted file & print text
  print("\n")
  print(decrypted_text)
  with open("decrypted_text.txt", "w") as outfile:
    outfile.write(decrypted_text)
  print("\n")
  print("New file created: decrypted_text.txt")


#Call Decryption Function
decrypt_file("encrypted_text.txt")


#File Comparison
def file_comparison(file1, file2):
  with open(file1, "r") as file01:
    text1 = file01.read()
  with open(file2, "r") as file02:
    text2 = file02.read()
  if text1 == text2:
    print("\n")
    print ("Decryption successful")
  else:
    print("\n")
    print ("Decryption unsuccessful")

#Call comparison function
file_comparison("decrypted_text.txt", "raw_text.txt")