# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wKhIELKCZHyeZurm3bPzCxy2SShgjfa8
"""

#Enter Inputs for Shift1 & Shift2
shift1 = int(input("Enter Shift 1: "))
shift2 = int(input("Enter Shift 2: "))

#Encryption function
def encrypte(filename):
  with open(filename, "r") as file:
    content = file.read()

    #First Requirement (lowercase)
    result = ""
    for char in content:
      if char.islower() and 'a' <= char <= 'm':
        new_char = chr(((ord(char) - ord('a') + shift1 * shift2) % 26) + ord('a'))
        result += new_char

      #Second Requiremnet (lowercase)
      elif char.islower() and 'n' <= char <= 'z':
        new_char = chr(((ord(char) - ord('a') - (shift1 + shift2)) % 26) + ord('a'))
        result += new_char

      #First Requirement (Uppercase)
      elif char.isupper() and "A" <= char <= "M":
        new_char = chr(((ord(char) - ord('a')) - shift1) %26 + ord('a'))
        reulst += new_char

      #Second requirement (Uppercase)
      elif char.isupper() and "N" <= char <= "Z":
        new_char = chr(((ord(char) - ord('a')) * shift2 ** 2) %26 + ord('s'))
        result += new_char

      else:
        result += char





  return (result)


encrypte("raw_text.txt")